name: edutek
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  auth_buttons: 3.0.0
  audioplayers: ^3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/audio/
  fonts: 
    - family: Overpass
      fonts: 
        - asset: assets/fonts/Overpass-Regular.ttf
        - asset: assets/fonts/Overpass-SemiBold.ttf
  uses-material-design: true

